
commands = [
    "plasma-apply-colorscheme BreezeDark && plasma-apply-colorscheme Carbon",
    "hyprctl reload",
    "quickshell --config ~/.carbon/shell/quickshell ipc call theme update",
]

[colorfiles]
json      = "~/.carbon/shell/quickshell/theme/color.json"
rofi      = "~/.carbon/shell/rofi/theme/color.rasi"
hypr      = "~/.carbon/hypr/color.conf"

kde       = "~/.local/share/color-schemes/Carbon.colors"

# kitty     = "~/.config/kitty/color.conf"
# alacritty = "~/.config/alacritty/color.toml"
