
commands = [
    "plasma-apply-colorscheme BreezeDark && plasma-apply-colorscheme Carbon",
    "hyprctl reload",
    "quickshell --config ~/.carbon/shell/quickshell ipc call theme update",
]

[colorfiles]
rofi      = "~/.carbon/shell/rofi/Config/color.rasi"
json      = "~/.carbon/shell/quickshell/Config/color.json"
kde       = "~/.local/share/color-schemes/Carbon.colors"

hypr      = "~/.carbon/hypr/color.conf"


# kitty     = "~/.config/kitty/color.conf"
# alacritty = "~/.config/alacritty/color.toml"
