
[user]


[defaults]
# default terminal
terminal = "alacritty" 

# Source Directory for wallpapers
# Can be a single path or a list of paths
wallpaperSource = [
    "~/Pictures", "~/Images"
]


[theme]

# Profile Picture. 
face = "~/.carbon/assets/default_face.jpg"

# Applied wallpaper. ~ supported.
wallpaper = "~/.carbon/assets/default_wallpaper.jpg"

# Theme mode. 
# Valid values: dark, light
mode = "light"

# Theme variants. 
# Valid values: ash, coal, graphite, diamond
variant = "graphite"

# Theme contrast
contrast = 0.5


