
# general

general {
    lock_cmd = carbon-shell power lock
    # Lock command
    
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    # so screen wakes up instantly
}

# listeners and their timeouts

listener {
    timeout = 450
    on-timeout = carbon-shell backlight save && carbon-shell backlight set --value 20
    on-resume = carbon-shell backlight restore     
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session  
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off                            
    on-resume = hyprctl dispatch dpms on  
}

