
pragma Singleton

import QtQuick
import Quickshell

Singleton 
{
    property color invisible					 : "#00000000"

	property color background                    : "#0a1519"
	property color surface                       : "#0a1519"
	property color surface_dim                   : "#0a1519"
	property color surface_bright                : "#303b3f"
	property color surface_container_lowest      : "#051013"
	property color surface_container_low         : "#121d21"
	property color surface_container             : "#162125"
	property color surface_container_high        : "#212c30"
	property color surface_container_highest     : "#2b373b"
	property color on_surface                    : "#d8e4ea"
	property color surface_variant               : "#3a494e"
	property color on_surface_variant            : "#b9c9d0"
	property color inverse_surface               : "#d8e4ea"
	property color inverse_on_surface            : "#273236"
	property color outline                       : "#849399"
	property color outline_variant               : "#3a494e"
	property color shadow                        : "#000000"
	property color scrim                         : "#000000"
	property color surface_tint                  : "#37d7ff"
	property color primary                       : "#37d7ff"
	property color on_primary                    : "#003642"
	property color primary_container             : "#004e5f"
	property color on_primary_container          : "#b3ebff"
	property color inverse_primary               : "#00677d"
	property color secondary                     : "#aacbe4"
	property color on_secondary                  : "#103447"
	property color secondary_container           : "#2a4a5f"
	property color on_secondary_container        : "#c7e7ff"
	property color tertiary                      : "#a8c9f6"
	property color on_tertiary                   : "#093257"
	property color tertiary_container            : "#26486f"
	property color on_tertiary_container         : "#d2e4ff"
	property color error                         : "#ffb4ab"
	property color on_error                      : "#690005"
	property color error_container               : "#93000a"
	property color on_error_container            : "#ffdad6"
	property color primary_fixed                 : "#b3ebff"
	property color primary_fixed_dim             : "#37d7ff"
	property color on_primary_fixed              : "#001f27"
	property color on_primary_fixed_variant      : "#004e5f"
	property color secondary_fixed               : "#c7e7ff"
	property color secondary_fixed_dim           : "#aacbe4"
	property color on_secondary_fixed            : "#001e2e"
	property color on_secondary_fixed_variant    : "#2a4a5f"
	property color tertiary_fixed                : "#d2e4ff"
	property color tertiary_fixed_dim            : "#a8c9f6"
	property color on_tertiary_fixed             : "#001c37"
	property color on_tertiary_fixed_variant     : "#26486f"

}