
pragma Singleton

import QtQuick
import Quickshell

Singleton 
{
property color invisible					 : "#00000000"
property color background                    : "#0f150b"
property color surface                       : "#0f150b"
property color surface_dim                   : "#0f150b"
property color surface_bright                : "#353b30"
property color surface_container_lowest      : "#0a1007"
property color surface_container_low         : "#171d13"
property color surface_container             : "#1b2217"
property color surface_container_high        : "#262c21"
property color surface_container_highest     : "#30372c"
property color on_surface                    : "#dee5d4"
property color surface_variant               : "#3f4a38"
property color on_surface_variant            : "#bfcab3"
property color inverse_surface               : "#dee5d4"
property color inverse_on_surface            : "#2c3227"
property color outline                       : "#89947f"
property color outline_variant               : "#3f4a38"
property color shadow                        : "#000000"
property color scrim                         : "#000000"
property color surface_tint                  : "#78de48"
property color primary                       : "#78de48"
property color on_primary                    : "#113800"
property color primary_container             : "#47aa12"
property color on_primary_container          : "#0f3600"
property color inverse_primary               : "#276c00"
property color secondary                     : "#a0d583"
property color on_secondary                  : "#113800"
property color secondary_container           : "#24510e"
property color on_secondary_container        : "#90c374"
property color tertiary                      : "#76de4a"
property color on_tertiary                   : "#0f3900"
property color tertiary_container            : "#44aa16"
property color on_tertiary_container         : "#0d3600"
property color error                         : "#ffb4ab"
property color on_error                      : "#690005"
property color error_container               : "#93000a"
property color on_error_container            : "#ffdad6"
property color primary_fixed                 : "#93fb62"
property color primary_fixed_dim             : "#78de48"
property color on_primary_fixed              : "#072100"
property color on_primary_fixed_variant      : "#1c5200"
property color secondary_fixed               : "#bcf29d"
property color secondary_fixed_dim           : "#a0d583"
property color on_secondary_fixed            : "#072100"
property color on_secondary_fixed_variant    : "#24510e"
property color tertiary_fixed                : "#91fc64"
property color tertiary_fixed_dim            : "#76de4a"
property color on_tertiary_fixed             : "#062100"
property color on_tertiary_fixed_variant     : "#195200"

}