
label {
  monitor = 
  text = cmd[update:1000] date +"%I:%M"
  color = $onSurface
  font_size = 180
  font_family = Iosevka Bold
  position = 0, 60
  halign = center
  valign = center
}

shape {
	monitor =
	color = $background
	size = 100%, 60
	border_size = 0
    border_color = $primary
	rounding = 0
	position = 0, -4
	halign = center
    valign = bottom
}

image {
    monitor =
    path = ~/.carbon/user/face
    size = 160
    rounding = -1
    
	border_size = 4
    border_color = $onSurface

    position = 30, 10
    halign = left
    valign = bottom
}	

label {
    monitor =
    text = cmd[update:1000] echo "Hi $(whoami)! :P"
    color = $onSurface
    font_size = 14
    font_family = Iosevka Italic
    position = 220, 16
	halign = left
    valign = bottom
}

label {
	monitor =
	text = cmd[update:1000] date +"%A, %B %d %Y"
	color = $onSurface
	font_size = 14
	font_family = Iosevka
	position = -20, 16
	halign = right
	valign = bottom
}

input-field {
    monitor =
    size = 400, 50
    outline_thickness = 4
    outer_color = $surfaceContainer
    inner_color = $background

    check_color = $onSurface
    fail_color = $error
    capslock_color = $tertiary

    font_color = $onSurface
    fade_on_empty = false
    rounding = 20

    font_family = Iosevka
    placeholder_text = Enter password...
    fail_text = $FAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

	position = 0, 180
    halign = center
    valign = bottom
}
